[add] footer and their items
platzi/platzi-music pull request #2
Opened 2017-04-03 23:13 UTC by HenryTabima

2017-04-03 23:30 UTC, LeonidasEsteban approved these changes

2017-04-04 16:24 UTC, LeonidasEsteban requested changes

2017-04-04 16:24 UTC, LeonidasEsteban commented on components/Footer.js
> +    item1: {
pon esto como un json aparte que traigas a este archivo o ponlos en el store

2017-04-04 16:24 UTC, LeonidasEsteban commented on components/FooterItem.js
> +const Text = styled.p`
Text no hace nada, borrarlo

2017-04-04 16:24 UTC, LeonidasEsteban commented on components/FooterItem.js
> +  font-family: 'Quicksand';
la fuente está en los archivos de estilo globales

2017-04-04 19:23 UTC, HenryTabima commented on components/FooterItem.js
> +  font-family: 'Quicksand';
no entiendo que se requiere hacer aquí... quito el font family?

2017-04-04 19:37 UTC, LeonidasEsteban commented on components/FooterItem.js
> +  font-family: 'Quicksand';
si, mira lib/global.js ya agrega ese font-size en el body, entonces no hace falta ponerla en otro lugar.

2017-04-04 20:39 UTC, HenryTabima commented on components/FooterItem.js
> +  font-family: 'Quicksand';
aaahhh ok

2017-04-04 23:28 UTC, LeonidasEsteban approved these changes

2017-04-04 23:28 UTC, LeonidasEsteban commented on components/FooterItem.js
> +  font-family: 'Quicksand';
ya casi lo tiene, quita es linea y va el merge

2017-04-04 23:29 UTC, merged